//
//  ModelType.swift
//  
//
//  Created by Kevin Waltz on 29.09.22.
//

import Foundation

public struct ModelType {
    static let allTypes: [String: DeviceName] = ["i386": .simulator,
                                                 "x86_64": .simulator,
                                                 "arm64": .simulator,
                                                 "iPhone8,4": .iPhoneSE,
                                                 "iPhone9,1": .iPhone7,
                                                 "iPhone9,2": .iPhone7Plus,
                                                 "iPhone9,3": .iPhone7,
                                                 "iPhone9,4": .iPhone7Plus,
                                                 "iPhone10,1": .iPhone8,
                                                 "iPhone10,2": .iPhone8Plus,
                                                 "iPhone10,3": .iPhoneXGlobal,
                                                 "iPhone10,4": .iPhone8,
                                                 "iPhone10,5": .iPhone8Plus,
                                                 "iPhone10,6": .iPhoneXGSM,
                                                 "iPhone11,2": .iPhoneXS,
                                                 "iPhone11,4": .iPhoneXSMax,
                                                 "iPhone11,6": .iPhoneXSMaxGlobal,
                                                 "iPhone11,8": .iPhoneXR,
                                                 "iPhone12,1": .iPhone11,
                                                 "iPhone12,3": .iPhone11Pro,
                                                 "iPhone12,5": .iPhone11ProMax,
                                                 "iPhone12,8": .iPhoneSE2Gen,
                                                 "iPhone13,1": .iPhone12Mini,
                                                 "iPhone13,2": .iPhone12,
                                                 "iPhone13,3": .iPhone12Pro,
                                                 "iPhone13,4": .iPhone12ProMax,
                                                 "iPhone14,2": .iPhone13Pro,
                                                 "iPhone14,3": .iPhone13ProMax,
                                                 "iPhone14,4": .iPhone13Mini,
                                                 "iPhone14,5": .iPhone13,
                                                 "iPhone14,6": .iPhoneSE3Gen,
                                                 "iPhone14,7" : .iPhone14,
                                                 "iPhone14,8" : .iPhone14Plus,
                                                 "iPhone15,2" : .iPhone14Pro,
                                                 "iPhone15,3" : .iPhone14ProMax,
                                                 
                                                 "iPad6,3": .iPadPro97Wifi,
                                                 "iPad6,4": .iPadPro97WifiCell,
                                                 "iPad6,7": .iPadPro129Wifi,
                                                 "iPad6,8": .iPadPro129WifiCell,
                                                 "iPad6,11": .iPad2017,
                                                 "iPad6,12": .iPad2017,
                                                 "iPad7,1": .iPadProWifi2Gen,
                                                 "iPad7,2": .iPadProWifiCell2Gen,
                                                 "iPad7,3": .iPadPro1052Gen,
                                                 "iPad7,4": .iPadPro1052Gen,
                                                 "iPad7,5": .iPadWifi6Gen,
                                                 "iPad7,6": .iPadWifiCell6Gen,
                                                 "iPad7,11": .iPad102Wifi7Gen,
                                                 "iPad7,12": .iPad102WifiCell7Gen,
                                                 "iPad8,1": .iPadPro11Wifi3Gen,
                                                 "iPad8,2": .iPadPro11Wifi3Gen1TB,
                                                 "iPad8,3": .iPadPro11WifiCell3Gen,
                                                 "iPad8,4": .iPadPro11WifiCell3Gen1TB,
                                                 "iPad8,5": .iPadPro129Wifi3Gen,
                                                 "iPad8,6": .iPadPro129Wifi3Gen1TB,
                                                 "iPad8,7": .iPadPro129WifiCell3Gen,
                                                 "iPad8,8": .iPadPro129WifiCell3Gen1TB,
                                                 "iPad8,9": .iPadPro11Wifi4Gen,
                                                 "iPad8,10": .iPadPro11WifiCell4Gen,
                                                 "iPad8,11": .iPadPro129Wifi4Gen,
                                                 "iPad8,12": .iPadPro129WifiCell4Gen,
                                                 "iPad11,1": .iPadMiniWifi5Gen,
                                                 "iPad11,2": .iPadMini5Gen,
                                                 "iPad11,3": .iPadAirWifi3Gen,
                                                 "iPad11,4": .iPadAir3Gen,
                                                 "iPad11,6": .iPadWifi8Gen,
                                                 "iPad11,7": .iPadWifiCell8Gen,
                                                 "iPad12,1": .iPadWifi9Gen,
                                                 "iPad12,2": .iPadWifiCell9Gen,
                                                 "iPad14,1": .iPadMiniWifi6Gen,
                                                 "iPad14,2": .iPadMiniWifiCell6Gen,
                                                 "iPad13,1": .iPadAirWifi4Gen,
                                                 "iPad13,2": .iPadAirWifiCell4Gen,
                                                 "iPad13,4": .iPadPro115Gen,
                                                 "iPad13,5": .iPadPro115Gen,
                                                 "iPad13,6": .iPadPro115Gen,
                                                 "iPad13,7": .iPadPro115Gen,
                                                 "iPad13,8": .iPadPro1295Gen,
                                                 "iPad13,9": .iPadPro1295Gen,
                                                 "iPad13,10": .iPadPro1295Gen,
                                                 "iPad13,11": .iPadPro1295Gen,
                                                 "iPad13,16": .iPadAirWifi5Gen,
                                                 "iPad13,17": .iPadAirWifiCell5Gen]
}
